In [1]:
# Housing Data Analysis
#Absolute maximum scaling of housing data

In [2]:
#libraries
import pandas as pd
import numpy as np

df = pd.read_csv('housing.csv')
df.head()

   LotArea  MSSubClass
0     8450          60
1     9600          20
2    11250          60
3     9550          70
4    14260          60

In [3]:
df = df.select_dtypes(include=[np.number])  # Select only numeric columns
df.head(5)

   LotArea  MSSubClass
0     8450          60
1     9600          20
2    11250          60
3     9550          70
4    14260          60

In [ ]:

#maxscaling
max_abs = df.abs().max()  # Get the absolute maximum values for each column
#or
max_abs = np.max(np.abs(df), axis=0)  # Get the absolute maximum values for each column using NumPy
scaled_df = df / max_abs  # Scale the DataFrame by dividing by the absolute maximum values
scaled_df.head(5)  # Display the first 5 rows of the scaled DataFrame

    LotArea  MSSubClass
0  0.039258    0.315789
1  0.044600    0.105263
2  0.052266    0.315789
3  0.044368    0.368421
4  0.066250    0.315789